sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t sidxz/t-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sidxz/t-docker-react npm run test