sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t sidxz/t-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sidxz/t-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "t-docker-react"
  env: "Tdockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-230515820833"
  bucket_path: "t-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"